#lang ivy 1.7

    object updater = {
        type num
        interpret num -> bv[10]
        type exec_var
        interpret exec_var -> bv[8]
        type exec_stage
        interpret exec_stage -> bv[3]
        
        action incr(x:num) returns(y:num) = {
            y := x + 1
        }
        
        action decr(x:num) returns(y:num) = {
            y := x - 1
        }
    }

    
    object goal = {
        action achieved(v:updater.num)
        object spec = {
            before achieved {
                assert v >=  20;
                protocol.idle := 1
            }
        }
    }

    object enabled_checker = {

	action is_enabled_r1(reactant1:updater.num) returns(y:bool) = {
            if reactant1 >= 1 {
                y := true
            }
            else {
                y := false
            }
        }
            
        action is_enabled_r2(reactant1:updater.num) returns(y:bool) = {
            if reactant1 >= 1 {
                y := true
            }
            else {
                y := false
            }
        }
            
        action is_enabled_r3(reactant1:updater.num) returns(y:bool) = {
            if reactant1 >= 1 {
                y := true
            }
            else {
                y := false
            }
        }
            
        action is_enabled_r4(reactant1:updater.num) returns(y:bool) = {
            if reactant1 >= 1 {
                y := true
            }
            else {
                y := false
            }
        }
            
        action is_enabled_r5(reactant1:updater.num) returns(y:bool) = {
            if reactant1 >= 1 {
                y := true
            }
            else {
                y := false
            }
        }
            
        action is_enabled_r6(reactant1:updater.num) returns(y:bool) = {
            if reactant1 >= 1 {
                y := true
            }
            else {
                y := false
            }
        }
            
        action is_enabled_r7(reactant1:updater.num,reactant2:updater.num) returns(y:bool) = {
            if reactant1 >= 1 & reactant2 >= 1 {
                y := true
            }
            else {
                y := false
            }
        }
            
        action is_enabled_r8(reactant1:updater.num) returns(y:bool) = {
            if reactant1 >= 1 {
                y := true
            }
            else {
                y := false
            }
        }
            
        action is_enabled_r9(reactant1:updater.num,reactant2:updater.num) returns(y:bool) = {
            if reactant1 >= 1 & reactant2 >= 1 {
                y := true
            }
            else {
                y := false
            }
        }
            
        action is_enabled_r10(reactant1:updater.num) returns(y:bool) = {
            if reactant1 >= 1 {
                y := true
            }
            else {
                y := false
            }
        }
            
        action is_enabled_r11(reactant1:updater.num,reactant2:updater.num) returns(y:bool) = {
            if reactant1 >= 1 & reactant2 >= 1 {
                y := true
            }
            else {
                y := false
            }
        }
            
        action is_enabled_r12(reactant1:updater.num) returns(y:bool) = {
            if reactant1 >= 1 {
                y := true
            }
            else {
                y := false
            }
        }
            
        
}

object inspector = {
	action check_guard_r1(reactant1:updater.num)
	before check_guard_r1 {
            assert reactant1 >= 1
	}

	action check_guard_r2(reactant1:updater.num)
	before check_guard_r2 {
            assert reactant1 >= 1
	}

	action check_guard_r3(reactant1:updater.num)
	before check_guard_r3 {
            assert reactant1 >= 1
	}

	action check_guard_r4(reactant1:updater.num)
	before check_guard_r4 {
            assert reactant1 >= 1
	}

	action check_guard_r5(reactant1:updater.num)
	before check_guard_r5 {
            assert reactant1 >= 1
	}

	action check_guard_r6(reactant1:updater.num)
	before check_guard_r6 {
            assert reactant1 >= 1
	}

	action check_guard_r7(reactant1:updater.num,reactant2:updater.num)
	before check_guard_r7 {
            assert reactant1 >= 1 & reactant2 >= 1
	}

	action check_guard_r8(reactant1:updater.num)
	before check_guard_r8 {
            assert reactant1 >= 1
	}

	action check_guard_r9(reactant1:updater.num,reactant2:updater.num)
	before check_guard_r9 {
            assert reactant1 >= 1 & reactant2 >= 1
	}

	action check_guard_r10(reactant1:updater.num)
	before check_guard_r10 {
            assert reactant1 >= 1
	}

	action check_guard_r11(reactant1:updater.num,reactant2:updater.num)
	before check_guard_r11 {
            assert reactant1 >= 1 & reactant2 >= 1
	}

	action check_guard_r12(reactant1:updater.num)
	before check_guard_r12 {
            assert reactant1 >= 1
	}

	
}

object selector = {
	individual r1_exec : updater.exec_var
	individual r2_exec : updater.exec_var
	individual r3_exec : updater.exec_var
	individual r4_exec : updater.exec_var
	individual r5_exec : updater.exec_var
	individual r6_exec : updater.exec_var
	individual r7_exec : updater.exec_var
	individual r8_exec : updater.exec_var
	individual r9_exec : updater.exec_var
	individual r10_exec : updater.exec_var
	individual r11_exec : updater.exec_var
	individual r12_exec : updater.exec_var
	
	individual r1_rate : updater.exec_var
	individual r2_rate : updater.exec_var
	individual r3_rate : updater.exec_var
	individual r4_rate : updater.exec_var
	individual r5_rate : updater.exec_var
	individual r6_rate : updater.exec_var
	individual r7_rate : updater.exec_var
	individual r8_rate : updater.exec_var
	individual r9_rate : updater.exec_var
	individual r10_rate : updater.exec_var
	individual r11_rate : updater.exec_var
	individual r12_rate : updater.exec_var
	
	individual r1_count : updater.exec_var
	individual r2_count : updater.exec_var
	individual r3_count : updater.exec_var
	individual r4_count : updater.exec_var
	individual r5_count : updater.exec_var
	individual r6_count : updater.exec_var
	individual r7_count : updater.exec_var
	individual r8_count : updater.exec_var
	individual r9_count : updater.exec_var
	individual r10_count : updater.exec_var
	individual r11_count : updater.exec_var
	individual r12_count : updater.exec_var
	
	individual r1_count_rate : updater.exec_var
	individual r2_count_rate : updater.exec_var
	individual r3_count_rate : updater.exec_var
	individual r4_count_rate : updater.exec_var
	individual r5_count_rate : updater.exec_var
	individual r6_count_rate : updater.exec_var
	individual r7_count_rate : updater.exec_var
	individual r8_count_rate : updater.exec_var
	individual r9_count_rate : updater.exec_var
	individual r10_count_rate : updater.exec_var
	individual r11_count_rate : updater.exec_var
	individual r12_count_rate : updater.exec_var
	
	individual r1_stage : updater.exec_stage
	individual r2_stage : updater.exec_stage
	individual r3_stage : updater.exec_stage
	individual r4_stage : updater.exec_stage
	individual r5_stage : updater.exec_stage
	individual r6_stage : updater.exec_stage
	individual r7_stage : updater.exec_stage
	individual r8_stage : updater.exec_stage
	individual r9_stage : updater.exec_stage
	individual r10_stage : updater.exec_stage
	individual r11_stage : updater.exec_stage
	individual r12_stage : updater.exec_stage
	

	after init {
		r1_count := 0;
		r2_count := 0;
		r3_count := 0;
		r4_count := 0;
		r5_count := 0;
		r6_count := 0;
		r7_count := 0;
		r8_count := 0;
		r9_count := 0;
		r10_count := 0;
		r11_count := 0;
		r12_count := 0;
		

		r1_count_rate := 4;
		r2_count_rate := 4;
		r3_count_rate := 4;
		r4_count_rate := 4;
		r5_count_rate := 4;
		r6_count_rate := 4;
		r7_count_rate := 4;
		r8_count_rate := 4;
		r9_count_rate := 4;
		r10_count_rate := 4;
		r11_count_rate := 4;
		r12_count_rate := 4;
		
	}

	action execute_r1 returns(y:bool) = {
            r1_exec := r1_exec + 1;
            if r1_exec >= r1_rate {
                y := true;
                r1_exec := 0;
                r1_count := r1_count + 1
            }
            else {
                y := false
            };
            if r1_count >= r1_count_rate {
                r1_stage := r1_stage + 1;
                r1_count := 0;
                r1_count_rate := 4;
                r1_rate := 1
            }
            else if r1_stage = 1 {
                r1_count_rate := 3;
                r1_rate := 1
            }
            else if r1_stage = 2 {
                r1_count_rate := 5;
                r1_rate := 1
            }
            else if r1_stage = 3 {
                r1_count_rate := 4;
                r1_rate := 1
            }
            else if r1_stage = 4 {
                r1_count_rate := 4;
                r1_rate := 1
            }
            else if r1_stage = 5 {
                r1_count_rate := 5;
                r1_rate := 1
            }
            else if r1_stage = 6 {
                r1_count_rate := 3;
                r1_rate := 1
            }
            else if r1_stage = 7 {
                r1_count_rate := 4;
                r1_rate := 1
            }
            else {
                r1_stage := 0
            }
        }
        action execute_r2 returns(y:bool) = {
            r2_exec := r2_exec + 1;
            if r2_exec >= r2_rate {
                y := true;
                r2_exec := 0;
                r2_count := r2_count + 1
            }
            else {
                y := false
            };
            if r2_count >= r2_count_rate {
                r2_stage := r2_stage + 1;
                r2_count := 0;
                r2_count_rate := 4;
                r2_rate := 39
            }
            else if r2_stage = 1 {
                r2_count_rate := 3;
                r2_rate := 39
            }
            else if r2_stage = 2 {
                r2_count_rate := 5;
                r2_rate := 39
            }
            else if r2_stage = 3 {
                r2_count_rate := 4;
                r2_rate := 39
            }
            else if r2_stage = 4 {
                r2_count_rate := 4;
                r2_rate := 39
            }
            else if r2_stage = 5 {
                r2_count_rate := 5;
                r2_rate := 39
            }
            else if r2_stage = 6 {
                r2_count_rate := 3;
                r2_rate := 39
            }
            else if r2_stage = 7 {
                r2_count_rate := 4;
                r2_rate := 39
            }
            else {
                r2_stage := 0
            }
        }
        action execute_r3 returns(y:bool) = {
            r3_exec := r3_exec + 1;
            if r3_exec >= r3_rate {
                y := true;
                r3_exec := 0;
                r3_count := r3_count + 1
            }
            else {
                y := false
            };
            if r3_count >= r3_count_rate {
                r3_stage := r3_stage + 1;
                r3_count := 0;
                r3_count_rate := 4;
                r3_rate := 39
            }
            else if r3_stage = 1 {
                r3_count_rate := 3;
                r3_rate := 39
            }
            else if r3_stage = 2 {
                r3_count_rate := 5;
                r3_rate := 39
            }
            else if r3_stage = 3 {
                r3_count_rate := 4;
                r3_rate := 39
            }
            else if r3_stage = 4 {
                r3_count_rate := 4;
                r3_rate := 39
            }
            else if r3_stage = 5 {
                r3_count_rate := 5;
                r3_rate := 39
            }
            else if r3_stage = 6 {
                r3_count_rate := 3;
                r3_rate := 39
            }
            else if r3_stage = 7 {
                r3_count_rate := 4;
                r3_rate := 39
            }
            else {
                r3_stage := 0
            }
        }
        action execute_r4 returns(y:bool) = {
            r4_exec := r4_exec + 1;
            if r4_exec >= r4_rate {
                y := true;
                r4_exec := 0;
                r4_count := r4_count + 1
            }
            else {
                y := false
            };
            if r4_count >= r4_count_rate {
                r4_stage := r4_stage + 1;
                r4_count := 0;
                r4_count_rate := 4;
                r4_rate := 39
            }
            else if r4_stage = 1 {
                r4_count_rate := 3;
                r4_rate := 39
            }
            else if r4_stage = 2 {
                r4_count_rate := 5;
                r4_rate := 39
            }
            else if r4_stage = 3 {
                r4_count_rate := 4;
                r4_rate := 39
            }
            else if r4_stage = 4 {
                r4_count_rate := 4;
                r4_rate := 39
            }
            else if r4_stage = 5 {
                r4_count_rate := 5;
                r4_rate := 39
            }
            else if r4_stage = 6 {
                r4_count_rate := 3;
                r4_rate := 39
            }
            else if r4_stage = 7 {
                r4_count_rate := 4;
                r4_rate := 39
            }
            else {
                r4_stage := 0
            }
        }
        action execute_r5 returns(y:bool) = {
            r5_exec := r5_exec + 1;
            if r5_exec >= r5_rate {
                y := true;
                r5_exec := 0;
                r5_count := r5_count + 1
            }
            else {
                y := false
            };
            if r5_count >= r5_count_rate {
                r5_stage := r5_stage + 1;
                r5_count := 0;
                r5_count_rate := 4;
                r5_rate := 39
            }
            else if r5_stage = 1 {
                r5_count_rate := 3;
                r5_rate := 39
            }
            else if r5_stage = 2 {
                r5_count_rate := 5;
                r5_rate := 39
            }
            else if r5_stage = 3 {
                r5_count_rate := 4;
                r5_rate := 39
            }
            else if r5_stage = 4 {
                r5_count_rate := 4;
                r5_rate := 39
            }
            else if r5_stage = 5 {
                r5_count_rate := 5;
                r5_rate := 39
            }
            else if r5_stage = 6 {
                r5_count_rate := 3;
                r5_rate := 39
            }
            else if r5_stage = 7 {
                r5_count_rate := 4;
                r5_rate := 39
            }
            else {
                r5_stage := 0
            }
        }
        action execute_r6 returns(y:bool) = {
            r6_exec := r6_exec + 1;
            if r6_exec >= r6_rate {
                y := true;
                r6_exec := 0;
                r6_count := r6_count + 1
            }
            else {
                y := false
            };
            if r6_count >= r6_count_rate {
                r6_stage := r6_stage + 1;
                r6_count := 0;
                r6_count_rate := 4;
                r6_rate := 39
            }
            else if r6_stage = 1 {
                r6_count_rate := 3;
                r6_rate := 39
            }
            else if r6_stage = 2 {
                r6_count_rate := 5;
                r6_rate := 39
            }
            else if r6_stage = 3 {
                r6_count_rate := 4;
                r6_rate := 39
            }
            else if r6_stage = 4 {
                r6_count_rate := 4;
                r6_rate := 39
            }
            else if r6_stage = 5 {
                r6_count_rate := 5;
                r6_rate := 39
            }
            else if r6_stage = 6 {
                r6_count_rate := 3;
                r6_rate := 39
            }
            else if r6_stage = 7 {
                r6_count_rate := 4;
                r6_rate := 39
            }
            else {
                r6_stage := 0
            }
        }
        action execute_r7 returns(y:bool) = {
            r7_exec := r7_exec + 1;
            if r7_exec >= r7_rate {
                y := true;
                r7_exec := 0;
                r7_count := r7_count + 1
            }
            else {
                y := false
            };
            if r7_count >= r7_count_rate {
                r7_stage := r7_stage + 1;
                r7_count := 0;
                r7_count_rate := 4;
                r7_rate := 39
            }
            else if r7_stage = 1 {
                r7_count_rate := 3;
                r7_rate := 39
            }
            else if r7_stage = 2 {
                r7_count_rate := 5;
                r7_rate := 39
            }
            else if r7_stage = 3 {
                r7_count_rate := 4;
                r7_rate := 39
            }
            else if r7_stage = 4 {
                r7_count_rate := 4;
                r7_rate := 39
            }
            else if r7_stage = 5 {
                r7_count_rate := 5;
                r7_rate := 39
            }
            else if r7_stage = 6 {
                r7_count_rate := 3;
                r7_rate := 39
            }
            else if r7_stage = 7 {
                r7_count_rate := 4;
                r7_rate := 39
            }
            else {
                r7_stage := 0
            }
        }
        action execute_r8 returns(y:bool) = {
            r8_exec := r8_exec + 1;
            if r8_exec >= r8_rate {
                y := true;
                r8_exec := 0;
                r8_count := r8_count + 1
            }
            else {
                y := false
            };
            if r8_count >= r8_count_rate {
                r8_stage := r8_stage + 1;
                r8_count := 0;
                r8_count_rate := 4;
                r8_rate := 39
            }
            else if r8_stage = 1 {
                r8_count_rate := 3;
                r8_rate := 39
            }
            else if r8_stage = 2 {
                r8_count_rate := 5;
                r8_rate := 39
            }
            else if r8_stage = 3 {
                r8_count_rate := 4;
                r8_rate := 39
            }
            else if r8_stage = 4 {
                r8_count_rate := 4;
                r8_rate := 39
            }
            else if r8_stage = 5 {
                r8_count_rate := 5;
                r8_rate := 39
            }
            else if r8_stage = 6 {
                r8_count_rate := 3;
                r8_rate := 39
            }
            else if r8_stage = 7 {
                r8_count_rate := 4;
                r8_rate := 39
            }
            else {
                r8_stage := 0
            }
        }
        action execute_r9 returns(y:bool) = {
            r9_exec := r9_exec + 1;
            if r9_exec >= r9_rate {
                y := true;
                r9_exec := 0;
                r9_count := r9_count + 1
            }
            else {
                y := false
            };
            if r9_count >= r9_count_rate {
                r9_stage := r9_stage + 1;
                r9_count := 0;
                r9_count_rate := 4;
                r9_rate := 39
            }
            else if r9_stage = 1 {
                r9_count_rate := 3;
                r9_rate := 39
            }
            else if r9_stage = 2 {
                r9_count_rate := 5;
                r9_rate := 39
            }
            else if r9_stage = 3 {
                r9_count_rate := 4;
                r9_rate := 39
            }
            else if r9_stage = 4 {
                r9_count_rate := 4;
                r9_rate := 39
            }
            else if r9_stage = 5 {
                r9_count_rate := 5;
                r9_rate := 39
            }
            else if r9_stage = 6 {
                r9_count_rate := 3;
                r9_rate := 39
            }
            else if r9_stage = 7 {
                r9_count_rate := 4;
                r9_rate := 39
            }
            else {
                r9_stage := 0
            }
        }
        action execute_r10 returns(y:bool) = {
            r10_exec := r10_exec + 1;
            if r10_exec >= r10_rate {
                y := true;
                r10_exec := 0;
                r10_count := r10_count + 1
            }
            else {
                y := false
            };
            if r10_count >= r10_count_rate {
                r10_stage := r10_stage + 1;
                r10_count := 0;
                r10_count_rate := 4;
                r10_rate := 39
            }
            else if r10_stage = 1 {
                r10_count_rate := 3;
                r10_rate := 39
            }
            else if r10_stage = 2 {
                r10_count_rate := 5;
                r10_rate := 39
            }
            else if r10_stage = 3 {
                r10_count_rate := 4;
                r10_rate := 39
            }
            else if r10_stage = 4 {
                r10_count_rate := 4;
                r10_rate := 39
            }
            else if r10_stage = 5 {
                r10_count_rate := 5;
                r10_rate := 39
            }
            else if r10_stage = 6 {
                r10_count_rate := 3;
                r10_rate := 39
            }
            else if r10_stage = 7 {
                r10_count_rate := 4;
                r10_rate := 39
            }
            else {
                r10_stage := 0
            }
        }
        action execute_r11 returns(y:bool) = {
            r11_exec := r11_exec + 1;
            if r11_exec >= r11_rate {
                y := true;
                r11_exec := 0;
                r11_count := r11_count + 1
            }
            else {
                y := false
            };
            if r11_count >= r11_count_rate {
                r11_stage := r11_stage + 1;
                r11_count := 0;
                r11_count_rate := 4;
                r11_rate := 39
            }
            else if r11_stage = 1 {
                r11_count_rate := 3;
                r11_rate := 39
            }
            else if r11_stage = 2 {
                r11_count_rate := 5;
                r11_rate := 39
            }
            else if r11_stage = 3 {
                r11_count_rate := 4;
                r11_rate := 39
            }
            else if r11_stage = 4 {
                r11_count_rate := 4;
                r11_rate := 39
            }
            else if r11_stage = 5 {
                r11_count_rate := 5;
                r11_rate := 39
            }
            else if r11_stage = 6 {
                r11_count_rate := 3;
                r11_rate := 39
            }
            else if r11_stage = 7 {
                r11_count_rate := 4;
                r11_rate := 39
            }
            else {
                r11_stage := 0
            }
        }
        action execute_r12 returns(y:bool) = {
            r12_exec := r12_exec + 1;
            if r12_exec >= r12_rate {
                y := true;
                r12_exec := 0;
                r12_count := r12_count + 1
            }
            else {
                y := false
            };
            if r12_count >= r12_count_rate {
                r12_stage := r12_stage + 1;
                r12_count := 0;
                r12_count_rate := 4;
                r12_rate := 39
            }
            else if r12_stage = 1 {
                r12_count_rate := 3;
                r12_rate := 39
            }
            else if r12_stage = 2 {
                r12_count_rate := 5;
                r12_rate := 39
            }
            else if r12_stage = 3 {
                r12_count_rate := 4;
                r12_rate := 39
            }
            else if r12_stage = 4 {
                r12_count_rate := 4;
                r12_rate := 39
            }
            else if r12_stage = 5 {
                r12_count_rate := 5;
                r12_rate := 39
            }
            else if r12_stage = 6 {
                r12_count_rate := 3;
                r12_rate := 39
            }
            else if r12_stage = 7 {
                r12_count_rate := 4;
                r12_rate := 39
            }
            else {
                r12_stage := 0
            }
        }
        
}

object protocol = {

	type 2bit
	interpret 2bit -> bv[1]
	individual idle : 2bit

	individual r_codY : updater.num
	individual r_flache : updater.num
	individual r_SigD_hag : updater.num
	individual r_hag : updater.num
	individual r_CodY_flache : updater.num
	individual r_CodY_hag : updater.num
	individual r_CodY : updater.num
	individual r_SigD : updater.num
	individual r_Hag : updater.num

	after init {
		r_codY := 1;
		r_flache := 1;
		r_SigD_hag := 1;
		r_hag := 1;
		r_CodY_flache := 1;
		r_CodY_hag := 1;
		r_CodY := 11;
		r_SigD := 10;
		r_Hag := 10;
		idle := 0
	}

	action update_r1 =  {
            if selector.execute_r1 {
			call inspector.check_guard_r1(r_codY);
			r_codY := updater.decr(r_codY);
			r_codY := updater.incr(r_codY);
			r_CodY := updater.incr(r_CodY);
			if r_CodY >= 20 {
				call goal.achieved(r_CodY)
			}
		}
	}

	action update_r2 =  {
            if selector.execute_r2 {
			call inspector.check_guard_r2(r_CodY);
			r_CodY := updater.decr(r_CodY)
		}
	}

	action update_r3 =  {
            if selector.execute_r3 {
			call inspector.check_guard_r3(r_flache);
			r_flache := updater.decr(r_flache);
			r_flache := updater.incr(r_flache);
			r_SigD := updater.incr(r_SigD)
		}
	}

	action update_r4 =  {
            if selector.execute_r4 {
			call inspector.check_guard_r4(r_SigD);
			r_SigD := updater.decr(r_SigD)
		}
	}

	action update_r5 =  {
            if selector.execute_r5 {
			call inspector.check_guard_r5(r_SigD_hag);
			r_SigD_hag := updater.decr(r_SigD_hag);
			r_SigD := updater.incr(r_SigD);
			r_hag := updater.incr(r_hag);
			r_Hag := updater.incr(r_Hag)
		}
	}

	action update_r6 =  {
            if selector.execute_r6 {
			call inspector.check_guard_r6(r_Hag);
			r_Hag := updater.decr(r_Hag)
		}
	}

	action update_r7 =  {
            if selector.execute_r7 {
			call inspector.check_guard_r7(r_SigD,r_hag);
			r_SigD := updater.decr(r_SigD);
			r_hag := updater.decr(r_hag);
			r_SigD_hag := updater.incr(r_SigD_hag)
		}
	}

	action update_r8 =  {
            if selector.execute_r8 {
			call inspector.check_guard_r8(r_SigD_hag);
			r_SigD_hag := updater.decr(r_SigD_hag);
			r_SigD := updater.incr(r_SigD);
			r_hag := updater.incr(r_hag)
		}
	}

	action update_r9 =  {
            if selector.execute_r9 {
			call inspector.check_guard_r9(r_CodY,r_flache);
			r_CodY := updater.decr(r_CodY);
			r_flache := updater.decr(r_flache);
			r_CodY_flache := updater.incr(r_CodY_flache)
		}
	}

	action update_r10 =  {
            if selector.execute_r10 {
			call inspector.check_guard_r10(r_CodY_flache);
			r_CodY_flache := updater.decr(r_CodY_flache);
			r_CodY := updater.incr(r_CodY);
			r_flache := updater.incr(r_flache)
		}
	}

	action update_r11 =  {
            if selector.execute_r11 {
			call inspector.check_guard_r11(r_CodY,r_hag);
			r_CodY := updater.decr(r_CodY);
			r_hag := updater.decr(r_hag);
			r_CodY_hag := updater.incr(r_CodY_hag)
		}
	}

	action update_r12 =  {
            if selector.execute_r12 {
			call inspector.check_guard_r12(r_CodY_hag);
			r_CodY_hag := updater.decr(r_CodY_hag);
			r_CodY := updater.incr(r_CodY);
			r_hag := updater.incr(r_hag)
		}
	}

	

	action idling = {}

	

	action fail_test = {}

	before update_r1 {
		assert idle = 0;
		assert enabled_checker.is_enabled_r1(r_codY)
	}
	before update_r2 {
		assert idle = 0;
		assert enabled_checker.is_enabled_r2(r_CodY)
	}
	before update_r3 {
		assert idle = 0;
		assert enabled_checker.is_enabled_r3(r_flache)
	}
	before update_r4 {
		assert idle = 0;
		assert enabled_checker.is_enabled_r4(r_SigD)
	}
	before update_r5 {
		assert idle = 0;
		assert enabled_checker.is_enabled_r5(r_SigD_hag)
	}
	before update_r6 {
		assert idle = 0;
		assert enabled_checker.is_enabled_r6(r_Hag)
	}
	before update_r7 {
		assert idle = 0;
		assert enabled_checker.is_enabled_r7(r_SigD,r_hag)
	}
	before update_r8 {
		assert idle = 0;
		assert enabled_checker.is_enabled_r8(r_SigD_hag)
	}
	before update_r9 {
		assert idle = 0;
		assert enabled_checker.is_enabled_r9(r_CodY,r_flache)
	}
	before update_r10 {
		assert idle = 0;
		assert enabled_checker.is_enabled_r10(r_CodY_flache)
	}
	before update_r11 {
		assert idle = 0;
		assert enabled_checker.is_enabled_r11(r_CodY,r_hag)
	}
	before update_r12 {
		assert idle = 0;
		assert enabled_checker.is_enabled_r12(r_CodY_hag)
	}
	

	before idling {
		assert idle = 1
	}


	after idling {
		assert idle = 0
	}



	before fail_test {
		assert idle = 0;
		assert (enabled_checker.is_enabled_r1(r_codY) = false & enabled_checker.is_enabled_r2(r_CodY) = false & enabled_checker.is_enabled_r3(r_flache) = false & enabled_checker.is_enabled_r4(r_SigD) = false & enabled_checker.is_enabled_r5(r_SigD_hag) = false & enabled_checker.is_enabled_r6(r_Hag) = false & enabled_checker.is_enabled_r7(r_SigD,r_hag) = false & enabled_checker.is_enabled_r8(r_SigD_hag) = false & enabled_checker.is_enabled_r9(r_CodY,r_flache) = false & enabled_checker.is_enabled_r10(r_CodY_flache) = false & enabled_checker.is_enabled_r11(r_CodY,r_hag) = false & enabled_checker.is_enabled_r12(r_CodY_hag) = false)
	}

	after fail_test {
		assert false
	}

}

export protocol.fail_test
export protocol.update_r1
export protocol.update_r2
export protocol.update_r3
export protocol.update_r4
export protocol.update_r5
export protocol.update_r6
export protocol.update_r7
export protocol.update_r8
export protocol.update_r9
export protocol.update_r10
export protocol.update_r11
export protocol.update_r12
export protocol.idling
import goal.achieved
import inspector.check_guard_r1
import inspector.check_guard_r2
import inspector.check_guard_r3
import inspector.check_guard_r4
import inspector.check_guard_r5
import inspector.check_guard_r6
import inspector.check_guard_r7
import inspector.check_guard_r8
import inspector.check_guard_r9
import inspector.check_guard_r10
import inspector.check_guard_r11
import inspector.check_guard_r12

isolate iso_proto = protocol with enabled_checker, updater, goal, selector, inspector